- name: Setup .bashrc
  hosts: localhost
  gather_facts: yes
  tasks: 
    - include_vars: vars.yaml
    - name: Ensure "{{ bash_config_dir }}" exists
      file:
        path: "{{ bash_config_dir }}"
        state: directory
        recurse: no
        mode: 0750
    - name: Ensure .bashrc sources dotfiles
      ansible.builtin.lineinfile:
        dest: "{{ ansible_env.HOME }}/.bashrc"
        create: yes
        state: present
        validate: grep -qv "^source {{ bash_config_dir }}" %s
        line: "source {{ bash_config_dir }}/*"
    - name: Link bash config scripts
      ansible.builtin.file:
        src: "{{ item }}"
        dest: "{{ bash_config_dir }}/{{ item | basename }}"
        state: link
      with_fileglob: "{{ dotfiles_path }}/bash/*.bashrc"
