- name: Install neovim
  hosts: localhost
  gather_facts: yes
  tasks: 
    - include_vars: vars.yaml
    - name: Download nightly nvim.appimage
      get_url:
        url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
        dest: "{{ nvim_path }}"
    - name: Make nvim.appimage executable
      file:
        path: "{{ nvim_path }}"
        mode: 0775
    - name: Install xclip
      become: yes
      package:
        name:
          - xclip
        state: present
    - name: Install ctags for coc-python (arch)
      when: ansible_facts['os_family'] == 'ArchLinux'
      become: yes
      package:
        name:
          - ctags
        state: present
    - name: Install ctags for coc-python (debian)
      when: ansible_facts['os_family'] == 'Debian'
      become: yes
      package:
        name:
          - exuberant-ctags
        state: present
